---
- hosts: all
  become: yes
  become_method: sudo
  collections:
    - devsec.hardening
  roles:
    - role: devsec.hardening.os_hardening
    - role: devsec.hardening.ssh_hardening
      vars:
        ssh_ciphers: ["aes128-ctr", "aes192-ctr", "aes256-ctr"]
        sshd_log_level: "INFO"
        ssh_client_alive_count: 0
        ssh_macs: ["hmac-sha2-512", "hmac-sha2-256"]
        ssh_banner: true
        ssh_banner_path: "/etc/ssh/banner"
    - role: geerlingguy.node_exporter
      vars:
        node_exporter_version: "1.1.2"
    - role: christiangda.amazon_cloudwatch_agent
      vars:
        cwa_agent_mode: "ec2"
        cwa_conf_json_file_content: "{{ lookup('file', 'cloudwatch-config.json') | from_json }}"
