---
- hosts: all
  name: Install Node Exporter
  become: yes
  become_method: sudo
  roles:
    - geerlingguy.node_exporter
    - "../ansible/roles/ansible-role-prometheus"
    - "../ansible/roles/ansible-role-grafana"
  vars:
    node_exporter_version: "1.1.2"
