---
- hosts: all
  name: Install Node Exporter and Prometheus
  become: yes
  become_method: sudo
  roles:
    - role: "../ansible/roles/ansible-role-prometheus"
    - role: "../ansible/roles/ansible-role-grafana"
