name: 'Terraform'
on: [push, pull_request]

jobs:
  check-format:
    strategy:
      matrix:
        paths: ['configuration',
        'monitoring/cloudwatch',
        'monitoring/prometheus',
        'networking/cloudfront',
        'networking/flowlogs',
        'networking/route53',
        'networking/transit-gateway',
        'networking/vpc-app',
        'networking/vpc-mgmt',
        'notifications/ses',
        'security/cloudtrail',
        'security/config/modules/aggregator',
        'security/config/modules/recorder',
        'security/guardduty',
        'security/iam',
        'security/scap',
        'security/security-groups',
        'security/waf',
        'services/imputation-server',
        'storage/mysql',
        'storage/s3']
    name: Check Format
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: terraform fmt
      uses: hashicorp/setup-terraform@v1
    - run: terraform fmt -check
      working-directory: ${{ matrix.paths }}
